### ISSUE TITLE
error!

### ISSUE THREAD

**Issue by mescalito** [lacymorrow/crossover#157]
---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.<anonymous> (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\src\main\auto-update.js:60:10)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:581:10)
    at Object.done (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:42:14)
    at done (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:719:25)
    at async NsisUpdater.executeDownload (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:757:12)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19042
Locale: en-US

**Comment by lacymorrow** [comment]
Hi @mescalito I have just fixed this, please update to the latest version to fix: https://github.com/lacymorrow/crossover/releases/latest

Thanks for submitting your error! It's the only way I know if something's wrong.
