### ISSUE TITLE
another error

### ISSUE THREAD

**Issue by mescalito** [lacymorrow/crossover#159]
---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.<anonymous> (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\src\main\auto-update.js:60:10)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:581:10)
    at Object.done (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:42:14)
    at done (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:719:25)
    at async NsisUpdater.executeDownload (C:\Users\Polaris\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:730:14)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19042
Locale: en-US

**Comment by lacymorrow** [comment]
Thanks so much for flagging! This is fixed in the latest version: https://github.com/lacymorrow/crossover/releases/latest
