### ISSUE TITLE
Ehhh This error is annoying me .. Can someone help me?

### ISSUE THREAD

**Issue by AngelKetch** [lacymorrow/crossover#161]
```
TypeError: Cannot read property 'setBadge' of undefined
    at NsisUpdater.<anonymous> (C:\Users\User\AppData\Local\Programs\crossover\resources\app.asar\src\main.js:154:14)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\User\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:382:14)
    at Object.done (C:\Users\User\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:29:22)
    at done (C:\Users\User\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:494:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async NsisUpdater.executeDownload (C:\Users\User\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:504:20)
```

---

CrossOver 2.7.4
Electron 12.2.3
win32 10.0.19043
Locale: pt-BR

**Comment by lacymorrow** [comment]
Hi, my apologies.
Please update to the latest version of CrossOver, this error has been fixed

Duplicate #153
