### ISSUE TITLE
Error when closing application

### ISSUE THREAD

**Issue by BreadSpriteBread** [lacymorrow/crossover#162]
Whenever I try to close or minimise the application the error pops up.

	---
	
	TypeError: Cannot read property 'showInactive' of undefined:
	TypeError: Cannot read property 'showInactive' of undefined
    at C:\Users\USER\AppData\Local\Programs\crossover\resources\app.asar\src\main\windows.js:357:19
    at each (C:\Users\USER\AppData\Local\Programs\crossover\resources\app.asar\src\main\windows.js:55:5)
    at Object.showWindow (C:\Users\USER\AppData\Local\Programs\crossover\resources\app.asar\src\main\windows.js:357:2)
    at IOHook.<anonymous> (C:\Users\USER\AppData\Local\Programs\crossover\resources\app.asar\src\main\iohook.js:86:12)
    at IOHook.emit (events.js:315:20)
    at IOHook._handler (C:\Users\USER\AppData\Local\Programs\crossover\resources\app.asar\node_modules\iohook\index.js:225:12)

	---

	CrossOver 3.0.1
Electron 11.5.0
win32 10.0.19043
Locale: en-GB

**Comment by lacymorrow** [comment]
duplicate #153
