### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hackmehust** [lacymorrow/crossover#167]
```
TypeError: Cannot read property 'setBadge' of undefined
    at NsisUpdater.<anonymous> (C:\Users\nhtha\AppData\Local\Programs\crossover\resources\app.asar\src\main.js:154:14)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\nhtha\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:382:14)
    at Object.done (C:\Users\nhtha\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:29:22)
    at done (C:\Users\nhtha\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:494:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async NsisUpdater.executeDownload (C:\Users\nhtha\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:504:20)
```

---

CrossOver 2.7.4
Electron 12.2.3
win32 10.0.22000
Locale: en-US

**Comment by lacymorrow** [comment]
This has been fixed, please update to the latest version, my apologies.
