### ISSUE TITLE
happens when i open crossover

### ISSUE THREAD

**Issue by NexusPlanet** [lacymorrow/crossover#168]
---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\allenlin0217\AppData\Local\Programs\crossover\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.onUpdateDownloaded (C:\Users\allenlin0217\AppData\Local\Programs\crossover\resources\app.asar\src\main\auto-update.js:51:7)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\allenlin0217\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:390:14)
    at Object.done (C:\Users\allenlin0217\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:29:22)
    at done (C:\Users\allenlin0217\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:502:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NsisUpdater.executeDownload (C:\Users\allenlin0217\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:512:20)

	---

	CrossOver 3.1.0
Electron 11.5.0
win32 6.3.9600
Locale: en-US

**Comment by lacymorrow** [comment]
Please update, duplicate #153
