### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ketoo34235** [lacymorrow/crossover#176]
```
TypeError: Cannot read property 'setBadge' of undefined
    at NsisUpdater.<anonymous> (C:\Users\pc\AppData\Local\Programs\crossover\resources\app.asar\src\main.js:154:14)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\pc\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:382:14)
    at Object.done (C:\Users\pc\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:29:22)
    at done (C:\Users\pc\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:494:31)
    at async NsisUpdater.executeDownload (C:\Users\pc\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:504:20)
```

---

CrossOver 2.7.4
Electron 12.2.3
win32 10.0.19043
Locale: en-US

**Comment by lacymorrow** [comment]
Hi @Ketoo34235, 

While I appreciate you flagging this error the first time, I don't appreciate the spam and abuse of the issue tracker by creating 5 separate issues, especially after I've commented on how to fix your particular problem.

The issue you are having has already been flagged in #153, making this a duplicate. 
Please update your version of CrossOver to fix the error, as stated in the issue above and many times before in your other issues.

Duplicate #153
