### ISSUE TITLE
crossover failed

### ISSUE THREAD

**Issue by grandturtle** [lacymorrow/crossover#187]
```
TypeError: Cannot read property 'setBadge' of undefined
    at NsisUpdater.<anonymous> (C:\Users\mille\AppData\Local\Programs\crossover\resources\app.asar\src\main.js:154:14)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\mille\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:382:14)
    at Object.done (C:\Users\mille\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:29:22)
    at done (C:\Users\mille\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:494:31)
    at async NsisUpdater.executeDownload (C:\Users\mille\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:504:20)
```

---

CrossOver 2.7.4
Electron 12.2.3
win32 10.0.22000
Locale: en-US

**Comment by lacymorrow** [comment]
Thanks for reporting! 
This has been fixed in the latest version of crossover, please update
