### ISSUE TITLE
Some sort of error dont know what to do

### ISSUE THREAD

**Issue by Aleth1** [lacymorrow/crossover#190]
---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\aleth\AppData\Local\Programs\crossover\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.onUpdateDownloaded (C:\Users\aleth\AppData\Local\Programs\crossover\resources\app.asar\src\main\auto-update.js:51:7)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\aleth\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:390:14)
    at Object.done (C:\Users\aleth\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:29:22)
    at done (C:\Users\aleth\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:502:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NsisUpdater.executeDownload (C:\Users\aleth\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:512:20)

	---

	CrossOver 3.1.0
Electron 11.5.0
win32 10.0.19043
Locale: nb

**Comment by lacymorrow** [comment]
This is fixed in the latest version, please update!

Duplicate #181
