### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by Poetic-Abortionist** [lacymorrow/crossover#211]
I get the following error whenever I start the program otherwise it works normal.

Unhandled Promise Rejection
TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:/Users/%user%/AppData/Local/Programs/crossover/resources/app.asar/src/main/dock.js:5:35)
    at NsisUpdater.onUpdateDownloaded (C:/Users/%user%/AppData/Local/Programs/crossover/resources/app.asar/src/main/auto-update.js:51:7)
    at NsisUpdater.dispatchUpdateDownloaded (C:/Users/%user%/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:390:14)
    at Object.done (C:/Users/%user%/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:29:22)
    at done (C:/Users/%user%/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:502:31)
    at async NsisUpdater.executeDownload (C:/Users/%user%/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:512:20)

**Comment by lacymorrow** [comment]
Duplicate #153 
Please update CrossOver, this is fixed.
