### ISSUE TITLE
Windows 10.0.1945 build 19045 error 

### ISSUE THREAD

**Issue by MADN00BIE** [lacymorrow/crossover#224]
---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\cxwxb\AppData\Local\Temp\27nT1730zuPVjkXuphKEn0qXaUQ\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.onUpdateDownloaded (C:\Users\cxwxb\AppData\Local\Temp\27nT1730zuPVjkXuphKEn0qXaUQ\resources\app.asar\src\main\auto-update.js:51:7)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\cxwxb\AppData\Local\Temp\27nT1730zuPVjkXuphKEn0qXaUQ\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:390:14)
    at Object.done (C:\Users\cxwxb\AppData\Local\Temp\27nT1730zuPVjkXuphKEn0qXaUQ\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:29:22)
    at done (C:\Users\cxwxb\AppData\Local\Temp\27nT1730zuPVjkXuphKEn0qXaUQ\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:502:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NsisUpdater.executeDownload (C:\Users\cxwxb\AppData\Local\Temp\27nT1730zuPVjkXuphKEn0qXaUQ\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:512:20)

	---

	CrossOver 3.1.0
Electron 11.5.0
win32 10.0.19045
Locale: en-US

**Comment by lacymorrow** [comment]
Please update your app version
