### ISSUE TITLE
작동은 하는데 어디서 충돌이 있는지 확인좀...

### ISSUE THREAD

**Issue by wodocuni** [lacymorrow/crossover#231]
```
TypeError: Cannot read property 'setBadge' of undefined
    at NsisUpdater.<anonymous> (C:\Users\내사랑 마둥이\AppData\Local\Programs\crossover\resources\app.asar\src\main.js:154:14)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\내사랑 마둥이\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:382:14)
    at Object.done (C:\Users\내사랑 마둥이\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:29:22)
    at done (C:\Users\내사랑 마둥이\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:494:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async NsisUpdater.executeDownload (C:\Users\내사랑 마둥이\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:504:20)
```

---

CrossOver 2.7.4
Electron 12.2.3
win32 10.0.19045
Locale: ko

**Comment by lacymorrow** [comment]
Update Crossover please.
