### ISSUE TITLE
Occasional error popup

### ISSUE THREAD

**Issue by n2sooners** [lacymorrow/crossover#239]
Just an occasional popup with an option to report the error. Doesn't seem to do anything to the app, but does interrupt game play at times. Haven't noticed any pattern.

	---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\n2soo\AppData\Local\Programs\crossover\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.<anonymous> (C:\Users\n2soo\AppData\Local\Programs\crossover\resources\app.asar\src\main\auto-update.js:60:10)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\n2soo\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:581:10)
    at Object.done (C:\Users\n2soo\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:42:14)
    at done (C:\Users\n2soo\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:719:25)
    at async NsisUpdater.executeDownload (C:\Users\n2soo\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:730:14)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19045
Locale: en-US

**Comment by lacymorrow** [comment]
update the app, duplicate #153
