### ISSUE TITLE
opaque crosshair container

### ISSUE THREAD

**Issue by xipecast** [lacymorrow/crossover#316]
when opened the window that contains the crosshair is opaque as opposed to transparent. The only fix I see is to restart.

	---
	
	Error: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory:
	Error: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/snap/crossover/16/resources/app.asar/node_modules/iohook/index.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)

	---

	CrossOver 3.0.0
Electron 11.5.0
linux 6.5.6-76060506-generic
Locale: en-US

**Comment by lacymorrow** [comment]
Duplicate #153 

This is every other issue, do you have a better idea of how to tell folks with this error to update the app?
