### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by RankBadjin** [lacymorrow/crossover#337]
Unhandled Promise Rejection
TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:/Users/lclay/AppData/Local/Programs/crossover/resources/app.asar/src/main/dock.js:5:35)
    at NsisUpdater.<anonymous> (C:/Users/lclay/AppData/Local/Programs/crossover/resources/app.asar/src/main/auto-update.js:60:10)
    at NsisUpdater.dispatchUpdateDownloaded (C:/Users/lclay/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:581:10)
    at Object.done (C:/Users/lclay/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:42:14)
    at done (C:/Users/lclay/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:719:25)
    at async NsisUpdater.executeDownload (C:/Users/lclay/AppData/Local/Programs/crossover/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:730:14)

**To Reproduce**

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10]
 - CrossOver Version [e.g. 3.2.0]

**Comment by florish-lacy** [comment]
Duplicate #181

**Comment by lacymorrow** [comment]
Please update
