### ISSUE TITLE
when i open my crosshair it says error and takes me to github

### ISSUE THREAD

**Issue by VexitaL1** [lacymorrow/crossover#341]
---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\ooffl\AppData\Local\Programs\crossover\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.<anonymous> (C:\Users\ooffl\AppData\Local\Programs\crossover\resources\app.asar\src\main\auto-update.js:60:10)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\ooffl\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:581:10)
    at Object.done (C:\Users\ooffl\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:42:14)
    at done (C:\Users\ooffl\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:719:25)
    at async NsisUpdater.executeDownload (C:\Users\ooffl\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:730:14)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.22621
Locale: en-US

**Comment by lacymorrow** [comment]
Please update. Duplicate #181
