### ISSUE TITLE
lhk;

### ISSUE THREAD

**Issue by haothiennvt** [lacymorrow/crossover#350]
---
	
	TypeError: Error processing argument at index 0, conversion failure from Shift+Scroll Lock:
	TypeError: Error processing argument at index 0, conversion failure from Shift+Scroll Lock
    at Object.registerShortcut (C:\Users\GT\AppData\Local\Programs\crossover\resources\app.asar\src\main\keyboard.js:25:56)
    at registerKeyboardShortcuts (C:\Users\GT\AppData\Local\Programs\crossover\resources\app.asar\src\main\crossover.js:154:13)
    at Object.syncSettings (C:\Users\GT\AppData\Local\Programs\crossover\resources\app.asar\src\main\crossover.js:367:2)
    at ElectronPreferences.<anonymous> (C:\Users\GT\AppData\Local\Programs\crossover\resources\app.asar\src\main\register.js:82:13)
    at ElectronPreferences.EventEmitter.emit (C:\Users\GT\AppData\Local\Programs\crossover\resources\app.asar\node_modules\eventemitter2\lib\eventemitter2.js:1011:19)
    at IpcMainImpl.<anonymous> (C:\Users\GT\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-preferences\index.js:168:9)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
    at Object.emit (events.js:315:20)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19045
Locale: en-US

**Comment by lacymorrow** [comment]
Where did you download the app?
Pleas update it. Duplicate #153
