### ISSUE TITLE
Crossover error warning window everytime 

### ISSUE THREAD

**Issue by Cloudingdang** [lacymorrow/crossover#357]
---
	
	Error: net::ERR_INTERNET_DISCONNECTED:
	Error: net::ERR_INTERNET_DISCONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6536)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19045
Locale: en-US

**Comment by lacymorrow** [comment]
https://github.com/lacymorrow/crossover/releases/tag/v3.3.4

Update
