### ISSUE TITLE
Error keeps popping up.

### ISSUE THREAD

**Issue by ani1nc** [lacymorrow/crossover#365]
---
	
	TypeError: Cannot read property 'getBounds' of undefined:
	TypeError: Cannot read property 'getBounds' of undefined
    at Object.appSize (C:\Users\poohf\AppData\Local\Programs\crossover\resources\app.asar\src\main\set.js:16:27)
    at Object.syncSettings (C:\Users\poohf\AppData\Local\Programs\crossover\resources\app.asar\src\main\crossover.js:282:6)
    at ElectronPreferences.<anonymous> (C:\Users\poohf\AppData\Local\Programs\crossover\resources\app.asar\src\main\register.js:82:13)
    at ElectronPreferences.EventEmitter.emit (C:\Users\poohf\AppData\Local\Programs\crossover\resources\app.asar\node_modules\eventemitter2\lib\eventemitter2.js:1011:19)
    at IpcMainImpl.<anonymous> (C:\Users\poohf\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-preferences\index.js:168:9)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
    at Object.emit (events.js:315:20)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19045
Locale: en-US

**Comment by lacymorrow** [comment]
📋 Tracked in Paperclip as **LAC-1339**. This issue has been added to our internal project management system and will be reviewed by the engineering team.

**Comment by lacymorrow** [comment]
📋 Tracked in Paperclip as **LAC-1763**. This issue has been added to our internal project management system and will be reviewed by the engineering team.

**Comment by lacymorrow** [comment]
📋 Tracked in Paperclip as **LAC-2544**. This issue has been added to our internal project management board and will be reviewed. [View in Paperclip](https://paperclip.ing/LAC/issues/LAC-2544)

**Comment by lacymorrow** [comment]
Tracked in Paperclip as **LAC-1339**. This issue has been added to our internal project management system and will be reviewed by the engineering team.

**Comment by lacymorrow** [comment]
Closing — this is two years old with no reproduction steps or error details. If you're still seeing errors on the current version, please open a new issue with the error message, your OS, and CrossOver version.
