### ISSUE TITLE
.  

### ISSUE THREAD

**Issue by Bezinnn** [lacymorrow/crossover#368]
---
	
	TypeError: Object has been destroyed:
	TypeError: Object has been destroyed
    at Object.hideChooserWindow (C:\Users\beleo\AppData\Local\Programs\crossover\resources\app.asar\src\main\windows.js:301:25)
    at Object.openSettingsWindow (C:\Users\beleo\AppData\Local\Programs\crossover\resources\app.asar\src\main\crossover.js:482:10)
    at IpcMainImpl.<anonymous> (C:\Users\beleo\AppData\Local\Programs\crossover\resources\app.asar\src\main\ipc.js:36:13)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
    at Object.emit (events.js:315:20)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.22621
Locale: en-US

**Comment by lacymorrow** [comment]
Where did you get the app?
Please update
