### ISSUE TITLE
crasht on computer wakeup

### ISSUE THREAD

**Issue by DarkofChaos** [lacymorrow/crossover#378]
---
	
	Error: net::ERR_INTERNET_DISCONNECTED:
	Error: net::ERR_INTERNET_DISCONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6536)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19045
Locale: de

**Comment by lacymorrow** [comment]
Please update
