### ISSUE TITLE
not sure why

### ISSUE THREAD

**Issue by mrishman** [lacymorrow/crossover#392]
---
	
	TypeError: Cannot read property 'getBounds' of undefined:
	TypeError: Cannot read property 'getBounds' of undefined
    at Object.appSize (C:\Users\Eban9\AppData\Local\Programs\crossover\resources\app.asar\src\main\set.js:16:27)
    at Object.syncSettings (C:\Users\Eban9\AppData\Local\Programs\crossover\resources\app.asar\src\main\crossover.js:282:6)
    at ElectronPreferences.<anonymous> (C:\Users\Eban9\AppData\Local\Programs\crossover\resources\app.asar\src\main\register.js:82:13)
    at ElectronPreferences.EventEmitter.emit (C:\Users\Eban9\AppData\Local\Programs\crossover\resources\app.asar\node_modules\eventemitter2\lib\eventemitter2.js:1011:19)
    at IpcMainImpl.<anonymous> (C:\Users\Eban9\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-preferences\index.js:168:9)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
    at Object.emit (events.js:315:20)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19045
Locale: en-GB

**Comment by lacymorrow** [comment]
Please update
