### ISSUE TITLE
Crossover doesn't work for me properly

### ISSUE THREAD

**Issue by GlobalCitizen2012** [lacymorrow/crossover#394]
![image_2024-11-07_044715988](https://github.com/user-attachments/assets/dde971f7-e759-4b42-ac52-f4863718ae6c)
![image_2024-11-07_044725427](https://github.com/user-attachments/assets/04f462a0-f41e-42b9-b983-3412d45fccee)
	

	---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\aydin\AppData\Local\Programs\crossover\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.<anonymous> (C:\Users\aydin\AppData\Local\Programs\crossover\resources\app.asar\src\main\auto-update.js:60:10)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\aydin\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:581:10)
    at Object.done (C:\Users\aydin\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:42:14)
    at done (C:\Users\aydin\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:719:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NsisUpdater.executeDownload (C:\Users\aydin\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:730:14)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.22631
Locale: en-US

**Comment by lacymorrow** [comment]
please update to the latest version
Duplicate #181
